export const countries = {
  countries: [
    "India",
    "United States",
    "China",
    "Japan",
    "Germany",
    "United Kingdom",
    "France",
    "Italy",
    "Brazil",
    "Canada",
    "Russia",
    "South Korea",
    "Australia",
    "Spain",
    "Mexico",
    "Indonesia",
    "Netherlands",
    "Saudi Arabia",
    "Turkey",
    "Switzerland",
    "Argentina",
    "Sweden",
    "Poland",
    "Belgium",
    "Thailand",
    "Iran",
    "Austria",
    "Norway",
    "United Arab Emirates",
    "Israel",
    "South Africa",
    "Denmark",
    "Singapore",
    "Malaysia",
    "Ireland",
    "Philippines",
    "Pakistan",
    "Chile",
    "Finland",
    "Portugal",
    "Greece",
    "Vietnam",
    "New Zealand",
    "Czech Republic",
    "Romania",
    "Hungary",
    "Kazakhstan",
    "Peru",
    "Iraq",
    "Qatar",
    "Bangladesh",
    "Kuwait",
    "Morocco",
    "Slovakia",
    "Angola",
    "Ecuador",
    "Sudan",
    "Sri Lanka",
    "Myanmar",
    "Oman",
    "Panama",
    "Uzbekistan",
    "Luxembourg",
    "Croatia",
    "Bahrain",
    "Ivory Coast",
    "Cameroon",
    "Nepal",
    "Uruguay",
    "Mongolia",
    "Paraguay",
    "Bolivia",
    "Trinidad and Tobago",
    "Afghanistan",
    "Estonia",
    "Cyprus",
    "Iceland",
    "Montenegro",
    "Malta",
    "Bhutan",
    "Barbados",
    "Brunei",
    "Belize",
    "Seychelles",
    "Saint Kitts and Nevis",
    "Liechtenstein",
    "Monaco",
    "San Marino",
    "Andorra",
    "Palau",
    "Marshall Islands",
  ],
};
